Components/TypesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WaterProject.Models;

namespace WaterProject.Components
{
    public class TypesViewComponent : ViewComponent
    {
        private IWaterProjectRepository repo { get; set; }

        public TypesViewComponent (IWaterProjectRepository temp)
        {
            repo = temp;
        }
        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedType = RouteData?.Values["projectType"];

            var types = repo.Projects
                .Select(x => x.ProjectType)
                .Distinct()
                .OrderBy(x => x);
            return View(types);
        }
    }
}

Views/Shared/ProjectSummary.cshtml
@{
}
@model Project




<br />
<div class="card card-outline-primary m-1 p-1">
    <div class="bg-light p-1">
        <h4>
            @Model.ProjectName
            <span class="badge bg-primary" style="float:right">
                <small>Impact: @Model.ProjectImpact Served</small>
            </span>
        </h4>
        <div class="card-text p-1">
            <ul>
                <li>Project Type: @Model.ProjectType</li>
                <li>Regional Program: @Model.ProjectRegionalProgram</li>
                <li>Project Phase: @Model.ProjectPhase</li>
                <li>Project Status: @Model.ProjectFunctionalityStatus</li>
            </ul>

            <form method="post" asp-page="/Donate">

                <input type="hidden" asp-for="@Model.ProjectId" />
                <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()"/>
                <span class="card-text">
                    <button type="submit" class="btn btn-success btn-sm float-end">Donate</button>

                </span>

            </form>
        </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <div class="bg-dark text-white p-2">
        <span class="navbar-brand ml-2">Water Project</span>
    </div>
    <div class="row m-1 p-1">
        <div id="types" class="col-3">
            <vc:types></vc:types>
        </div>
        <div class="col-9">
            <div>
                @RenderBody()
            </div>
        </div>
    </div>
</body>

</html>