Controllers/DonationController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WaterProject.Models;

namespace WaterProject.Controllers
{
    public class DonationController : Controller
    {
        private IDonationRepository repo { get; set; }
        private Basket basket { get; set; }
        public DonationController(IDonationRepository temp, Basket b)
        {
            repo = temp;
            basket = b;
        }

        [HttpGet]
        public IActionResult Checkout()
        {
            return View(new Donation());
        }

        [HttpPost]
        public IActionResult Checkout(Donation donation)
        {
            if (basket.Items.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your basket is empty!");
            }

            if (ModelState.IsValid)
            {
                donation.Lines = basket.Items.ToArray();
                repo.SaveDonation(donation);
                basket.ClearBasket();

                return RedirectToPage("/DonationCompleted");
            }

            else
            {
                return View();
            }
        }
    }
}

Pages/Donate.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WaterProject.Infrastructure;
using WaterProject.Models;

namespace WaterProject.Pages
{
    public class DonateModel : PageModel
    {
        private IWaterProjectRepository repo { get; set; }
        public DonateModel (IWaterProjectRepository temp, Basket b)
        {
            repo = temp;
            basket = b;
        }

        public Basket basket { get; set; }
        public string ReturnUrl { get; set; }
        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
        
        }

        public IActionResult OnPost(int projectId,string returnUrl)
        {
            Project p = repo.Projects.FirstOrDefault(x => x.ProjectId == projectId);

            
            basket.AddItem(p, 1);


            return RedirectToPage(new { ReturnUrl = returnUrl });
        }

        public IActionResult OnPostRemove(int projectId, string returnUrl)
        {
            basket.RemoveItem(basket.Items.First(x => x.Project.ProjectId == projectId).Project);

            return RedirectToPage( new {ReturnUrl = returnUrl});
        }
    }
}

Pages/DonationCompleted.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WaterProject.Pages
{
    public class DonationCompletedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Donate.cshtml
@page
@model WaterProject.Pages.DonateModel
@{
}

<h2>Your Basket</h2>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Item</th>
            <th>Quantity</th>
            <th>Cost</th>
            <th>Subtotal</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var i in Model.basket.Items)
            {
        <tr>
            <td>@i.Project.ProjectName</td>
            <td>@i.Quantity</td>
            <td>25</td>
            <td>@((i.Quantity * 25).ToString("c"))</td>

            <td class="text-center">
                <form method="post" asp-page-handler="Remove">
                    <input type="hidden" name="projectId" value="@i.Project.ProjectId" />
                    <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
                    <button type="submit" class="butn btn-sm btn-danger">Remove</button>
                </form>
            </td>

        </tr>
            }
    </tbody>

    <tfoot>
        <tr>
            <td colspan="3">Total:</td>
            <td>@Model.basket.CalculateTotal().ToString("c")</td>
        </tr>
    </tfoot>
</table>

<div>
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue Donating</a>
    <a class="btn btn-primary" asp-action="Checkout" asp-controller="Donation">Checkout</a>
</div>

Pages/DonationCompleted.cshtml
@page
@model WaterProject.Pages.DonationCompletedModel
@{
}

<div class="text-center">
    <h2> Thanks! Your order will make a difference!</h2>
    <a class="btn btn-primary" asp-controller="Home">Return Home</a>
</div>

Pages/_DonateLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <div class="bg-dark text-white p-2">
        Water Project
    </div>
    <div class="m-1 p-1">
        @RenderBody()
    </div>
</body>
</html>